export { getPathHospitalDetail } from './pathes';
export { getDistanceFromLocation } from './getDistanceFromLocation';
export { getErRTavailableBedByColor } from './getErRTavailableBedByColor';
export { copyText } from './copyText';
export { getDateStrByHvidate } from './getDateStrByHvidate';
export { classifySurgery } from './classifySurgery';
export { getHpRtHrAvailableBedData } from './getHpRtHrAvailableBedData';
export { classifyMsgSymTyp } from './classifyMsgSymTyp';
export { getFractionNumber } from './getFractionNumber';
