export { PATH_ROOT, PATH_CHARTVIEW, PATH_HOSPITALDETAIL } from './pathes';
export { SORTING_DISTANCE, SORTING_AVAILABLE_BED } from './sorting';
export {
  DEFAULT_LATITUDE,
  DEFAULT_LONGITUDE,
  DEFAULT_ADDRESS,
  DEFAULT_ROAD_ADDRESS,
} from './defaultLocation';
